name: firebasesample
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  google_sign_in: ^5.4.0
  cloud_firestore: ^3.3.0
  firebase_storage: ^10.3.2
  image_picker: ^0.8.5+3

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
